# Generated by Django 5.1.3 on 2024-11-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marvel',
            name='nombre_real',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
