# Generated by Django 5.1.3 on 2024-11-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_marvel_nombre_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='marvel',
            name='descripcion',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
