# Generated by Django 5.1.3 on 2024-11-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_marvel_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marvel',
            name='descripcion',
            field=models.CharField(default='Desconocido', max_length=500),
        ),
    ]
